name: "Matrix files"
description: "Generate a matrix for several files to upload to readme.io"
inputs:
  readme-id-file:
    description: "Path to readme.io json with file names and ids"
    required: true
    default: "readme.io.ids.json"
  files-filer-expression:
    description: "Filter expression to see filter files changed"
    required: true
    default: ""
  branch-nam:
    description: "The name of the branch to get the files"
    required: true
    default: ""
  github-token:
    description: "The github token to access files in repo see secrets.GITHUB_TOKEN "
    required: true
outputs:
  update-matrix:
    description: "The matrix files to update"
  create-list:
    description: "The list of files to be created"
runs:
  using: "node16"
  main: "dist/index.js"
