name: Test matrix request

on:
  push:
    branches: ["main"]

jobs:
  matrix-js-step:
    runs-on: ubuntu-latest
    name: Check the info filter files then do the matrix job
    steps:
      - name: ToMatrix
        uses: xrodrigux/matrix-js-action@main
        with:
          readme-id-file: "spec/readme.io.files.json"
          files-to-process: "portal-reg,portal-oauth2"
          github-token: ${{ secrets.GITHUB_TOKEN }}
